meta_product_name: "RV10"
meta_title: "Tu Catalogo Online - Ofertas que no podras rechazar"
meta_description: "Esta pagina web es un Look Book, todas las compras pueden ser hechas por whatsapp, formulario online, o en nuestras sucursales"
meta_image: "https://res.cloudinary.com/websy/image/upload/v1559528162/Screen_Shot_2019-06-02_at_10.15.24_PM.png" # should exist in `app/assets/images/`

